kind: Application
name: FIWARE_ENV
services:
  orion:
    container_name: orion
    image: fiware/orion:latest
    gateway: host
    ports:
      - 1026:1026
  mongo-db:
    container_name: mongo-db
    image: mongo:3.6
    gateway: host
    ports:
      - 27017:27017
